### ISSUE TITLE
Definir el título del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#1]

**Comment by noreidysRM** [comment]
<!DOCTYPE html>
<html lang="es">
<head>
    <title>Abordando la sexualidad</title>
</head>
<body>
    <h1>Abordando la sexualidad</h1>
</body>
</html>

**Comment by JohnFlorez25** [comment]
@JohnFlorez25 el título del proyecto ya se encuentra en la wiki
