### ISSUE TITLE
- [ ] Hacer flujo de tareas por funcionalidades

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#13]

**Comment by luisaqvillalobos** [comment]
<img src="https://fotos.subefotos.com/9afa9332f9a2314856ab470645ba95aao.jpg" />

**Comment by JohnFlorez25** [comment]
@luisaqvillalobos Los flujos de tareas por funcionalidades deben ser como mínimo 3, partiendo de la idea de que se tienen 10 historias de usuarios deberían ser estos en su totalidad, pero acepto que identifiquen mínimo 3.
