### ISSUE TITLE
- [ ] Implementar prototipos de alta fidelidad enfocándose en la navegabilidad y usabilidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#14]

**Comment by JohnFlorez25** [comment]
@manuela191219 @luisaqvillalobos @noreidysRM en la wiki les deje indicado el flujo principal que debe tener su aplicación de acuerdo a lo que hablamos en las asesorías pasadas donde deben garantizar:
- Iniciar sesión
- Registrar usuarios
- Temas ( mínimo dos temas)
- Niveles de aprendizaje por tema (mínimo dos niveles)
- Ranking de posición
- Perfil del usuario con su % de avance o puntos obtenidos
- Juego de (cuestionario, selección de imágenes, palabra correcta,  etc)

**Comment by luisaqvillalobos** [comment]
<a href="https://marvelapp.com/prototype/700iidb/screen/67114424"> ENLACE  DEL PROTOTIPO DE ALTA FIDELIDAD </a>
