### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#16]

**Comment by noreidysRM** [comment]
<img src="https://fotos.subefotos.com/85af21d5e8006d5ff2c21a88c46f8da9o.jpg"/>
<img src="https://fotos.subefotos.com/1310c42ee65be2290dd5e155e1f8bee5o.jpg"/>

**Comment by noreidysRM** [comment]
<img src="https://fotos.subefotos.com/1310c42ee65be2290dd5e155e1f8bee5o.jpg"/>
<img src="https://fotos.subefotos.com/85af21d5e8006d5ff2c21a88c46f8da9o.jpg"/>
