### ISSUE TITLE
- [ ] Definir los servicios del Backend que se deben implementar de acuerdo con las reglas de negocio. (Objeto JSON)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#17]

**Comment by JohnFlorez25** [comment]
@manuela191219 @luisaqvillalobos @noreidysRM El siguiente formato se especifica la estructura de como deben evidenciar cada uno de los servicios backend que van a ser consumidos desde el frontend
[Formato Definición de los servicios backend.docx](https://github.com/JohnFlorez25/equipo8_sn_ppi2020/files/5301401/Formato.Definicion.de.los.servicios.backend.docx)

**Comment by noreidysRM** [comment]
<img src="https://fotos.subefotos.com/0983eed55de2918bb833c4667455ec3eo.jpg"/>
<img src="https://fotos.subefotos.com/718c37e4d8017bf28ee9a46f45bef161o.jpg"/>
<img src="https://fotos.subefotos.com/9f029673e156c4ec21ca5c67faaf03beo.jpg"/>
