### ISSUE TITLE
- [ ] Diseño del modelo lógico de datos

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#18]

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @manuela191219 @luisaqvillalobos @noreidysRM teniendo en cuenta la implementación del modelo entidad relación una vez validado entre el/la docente y el asesor, realizar la construcción del modelo lógico de datos par ala construcción de los scripts de la base de datos

**Comment by noreidysRM** [comment]
<img src="https://fotos.subefotos.com/de2290b498491ce3ac9f32a6148828ado.jpg"/>
