### ISSUE TITLE
- [ ] Construcción de la BD haciendo uso de MySQL

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#19]

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @manuela191219 @manuela191219 @luisaqvillalobos @noreidysRM deben crear una carpeta llamada **bd** donde esten alojados los scripts para la creación de la base de datos

**Comment by noreidysRM** [comment]
<a href="https://github.com/noreidysRM/equipo8_sn_ppi2020/commit/32d0a3f6fda8dd7af137525524620963ba8552e7">URL DEL BD</a>
