### ISSUE TITLE
Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#2]

**Comment by noreidysRM** [comment]
<img src="https://thumbs.subefotos.com/7cc43aa4613f56e50b12a9f94fb8a211o.jpg">

**Comment by noreidysRM** [comment]
<src="https://fotos.subefotos.com/f57d91974717a14f9681d32da8710367o.png">

**Comment by noreidysRM** [comment]
[<a href="https://subefotos.com/ver/?f57d91974717a14f9681d32da8710367o.png" target="_blank"><img src="http://thumbs.subefotos.com/f57d91974717a14f9681d32da8710367o.jpg" /></a>](url)

**Comment by JohnFlorez25** [comment]
@noreidysRM @luisaqvillalobos el diagrama de espina de pescado solo se colocan las causas no las consecuencias, deben complementar los grupos de causas de acuerdo al análisis del problema que están abordando
