### ISSUE TITLE
Construir el tablero de visión del producto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#5]

**Comment by luisaqvillalobos** [comment]
#Descripción de Visión del Producto
### es un servicio para los jóvenes, docentes y estudiantes que necesitan información sobre la sexualidad. se llama abordando la sexualidad y es una aplicación web progresiva que ayudara a los jóvenes , docentes y estudiantes a utilizar la información para un buen vivir . nuestra pagina web permite que los jovenes, docentes y estudiantes aumenten la informacion sobre la sexualidad 
#Tablero de Visión del Producto
<a href="https://subefotos.com/ver/?62b6e3ec9942ed2a05edc02b97038992o.jpg" target="_blank"><img src="http://thumbs.subefotos.com/62b6e3ec9942ed2a05edc02b97038992o.jpg" /></a>
