### ISSUE TITLE
Preparar el pitch del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#7]

**Comment by noreidysRM** [comment]
<a href="https://subefotos.com/ver/?de46affa9a1563b11652a0b696bafd7co.png" target="_blank"><img src="http://thumbs.subefotos.com/de46affa9a1563b11652a0b696bafd7co.jpg" /></a>

<a href="https://subefotos.com/ver/?021c72e4880fdf5d9f5cc2666591c190o.png" target="_blank"><img src="http://thumbs.subefotos.com/021c72e4880fdf5d9f5cc2666591c190o.jpg" /></a>

<a href="https://subefotos.com/ver/?9caee05bc03102dae9865ce1cf08344co.png" target="_blank"><img src="http://thumbs.subefotos.com/9caee05bc03102dae9865ce1cf08344co.jpg" /></a>

<a href="https://subefotos.com/ver/?b57e78049d925efad673da7eed9a33cfo.png" target="_blank"><img src="http://thumbs.subefotos.com/b57e78049d925efad673da7eed9a33cfo.jpg" /></a>

<img stc="https://fotos.subefotos.com/b57e78049d925efad673da7eed9a33cfo.png" />
