### ISSUE TITLE
- [ ] Hacer mapa de Historia de Usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo8_sn_ppi2020#9]

**Comment by luisaqvillalobos** [comment]
<img ="https://fotos.subefotos.com/3aa6fc445bea66b4c176671dab88ec57o.jpg"/>

**Comment by luisaqvillalobos** [comment]
<img src="https://fotos.subefotos.com/3aa6fc445bea66b4c176671dab88ec57o.jpg"/>
